INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/eduardapodesta','eduarda viana podesta','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/ivancerboncini','ivan de campos cerboncini','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/felipehiga','felipe kenji higa','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/fernandothiers','fernando barbosa thiers','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/erikaalbizzati','erika couto albizzati','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/thiagobalbo','thiago duarte balbo','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/danielferreira','daniel breves ferreira','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/ramonmaciel','ramon carvalho maciel','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/tiagoferreira','tiago de lima ferreira','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/rafaelxavier','rafael xavier','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/nicholasmizoguchi','nicholas matuzita mizoguchi','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/tuliosilva','tulio bazan da silva','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/leonnardorabello','leonnardo chagas rabello','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/lukaslopes','lukas antunes lopes','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/rafaelgarcia','rafael matheus garcia','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/joaodalben','joao henrique dalben','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/caioteixeira','caio teixeira','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/elisadellarriva','elisa dellarriva','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/fernandogoncalves','fernando henrique dos santos goncalves','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/luanbicesto','luan gustavo bicesto','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/lucianosabenca','luciano padua sabenca','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/pedroalmeida','pedro cordeiro de almeida','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/tomasqueiroga','tomas silva queiroga','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/fabiolira','fabio maffei lira','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/guilhermemendes','guilherme da rocha alves mendes','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/guilhermemazzariol','guilherme sbrolini mazzariol','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/raphaelfranco','raphael marques franco','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/willianszati','willians hidalgo zati','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/victortavares','victor guilherme oliveira semedo tavares','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/fernandohoyo','fernando luiz del hoyo','campinas');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/lucasmello','lucas de campos mello','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/wilsonneto','wilson jose prata neto','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/andreiauratsuka','andreia yukie uratsuka','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/victorsilva','victor akira hassuda silva','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/leonardosilva','leonardo de oliveira silva','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/gabrielbezerra','gabriel massaki wakano bezerra','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/elvisrabello','elvis rabello','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/caiopalissari','caio vinicius uvini palissari','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/cibellebegalli','cibelle begalli','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/diegorocha','diego rocha','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/fellipecaetano','fellipe santiago scarpa caetano','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/gustavonunes','gustavo cesar nunes','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/juceliofonseca','jucelio evangelista fonseca','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/murilocruz','murilo de lima cruz','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/felipecaminada','felipe caminada','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/lucasbatista','lucas oliveira batista','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/andresantanche','andre santanche','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/luizgomes','Luiz Celso Gomes Jr','');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/lucaslima','Lucas Domingues Lima','Campinas');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/viniciussantos','Vinicius Pereira dos Santos','Campinas');
INSERT INTO Persons VALUES ('http://www.ic.unicamp.br/MC536/2014/1/diegosanches','Diego Sanches','Campinas');
